//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public int id { get; set; }
        public string quizname { get; set; }
        public string marks { get; set; }
        public string @true { get; set; }
        public string @false { get; set; }
        public Nullable<int> fk_studentid { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
